# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dennis/Projects/rapuma/lib/rapuma/dialog/main_dlg.ui'
#
# Created: Mon Mar 17 16:12:03 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 628)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidgetWorkArea = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidgetWorkArea.setGeometry(QtCore.QRect(10, 40, 782, 511))
        self.stackedWidgetWorkArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidgetWorkArea.setObjectName("stackedWidgetWorkArea")
        self.pageProject = QtGui.QWidget()
        self.pageProject.setObjectName("pageProject")
        self.labelProjectPid = QtGui.QLabel(self.pageProject)
        self.labelProjectPid.setGeometry(QtCore.QRect(75, 10, 181, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelProjectPid.setFont(font)
        self.labelProjectPid.setObjectName("labelProjectPid")
        self.labelProjectProject = QtGui.QLabel(self.pageProject)
        self.labelProjectProject.setGeometry(QtCore.QRect(10, 10, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelProjectProject.setFont(font)
        self.labelProjectProject.setObjectName("labelProjectProject")
        self.label_4 = QtGui.QLabel(self.pageProject)
        self.label_4.setGeometry(QtCore.QRect(40, 480, 131, 31))
        self.label_4.setObjectName("label_4")
        self.tabWidgetProject = QtGui.QTabWidget(self.pageProject)
        self.tabWidgetProject.setGeometry(QtCore.QRect(10, 50, 762, 430))
        self.tabWidgetProject.setObjectName("tabWidgetProject")
        self.tabGeneralSettings = QtGui.QWidget()
        self.tabGeneralSettings.setObjectName("tabGeneralSettings")
        self.lineEditProjectName = QtGui.QLineEdit(self.tabGeneralSettings)
        self.lineEditProjectName.setGeometry(QtCore.QRect(20, 30, 281, 27))
        self.lineEditProjectName.setObjectName("lineEditProjectName")
        self.tabWidgetProject.addTab(self.tabGeneralSettings, "")
        self.tabStyle = QtGui.QWidget()
        self.tabStyle.setObjectName("tabStyle")
        self.tabWidgetProject.addTab(self.tabStyle, "")
        self.tabTex = QtGui.QWidget()
        self.tabTex.setObjectName("tabTex")
        self.tabWidgetProject.addTab(self.tabTex, "")
        self.label_5 = QtGui.QLabel(self.pageProject)
        self.label_5.setGeometry(QtCore.QRect(230, 480, 131, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.pageProject)
        self.label_6.setGeometry(QtCore.QRect(410, 480, 150, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.pageProject)
        self.label_7.setGeometry(QtCore.QRect(640, 480, 66, 31))
        self.label_7.setObjectName("label_7")
        self.toolButton = QtGui.QToolButton(self.pageProject)
        self.toolButton.setGeometry(QtCore.QRect(632, 10, 40, 35))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Gnome-Document-Save-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(32, 32))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtGui.QToolButton(self.pageProject)
        self.toolButton_2.setGeometry(QtCore.QRect(682, 10, 40, 35))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Gnome-Weather-Overcast-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtGui.QToolButton(self.pageProject)
        self.toolButton_3.setGeometry(QtCore.QRect(732, 10, 40, 35))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Accessories-Dictionary-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_3.setObjectName("toolButton_3")
        self.stackedWidgetWorkArea.addWidget(self.pageProject)
        self.pageGroup = QtGui.QWidget()
        self.pageGroup.setObjectName("pageGroup")
        self.labelGroup = QtGui.QLabel(self.pageGroup)
        self.labelGroup.setGeometry(QtCore.QRect(10, 10, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelGroup.setFont(font)
        self.labelGroup.setObjectName("labelGroup")
        self.labelGroupGid = QtGui.QLabel(self.pageGroup)
        self.labelGroupGid.setGeometry(QtCore.QRect(65, 10, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelGroupGid.setFont(font)
        self.labelGroupGid.setObjectName("labelGroupGid")
        self.tabWidgetGroup = QtGui.QTabWidget(self.pageGroup)
        self.tabWidgetGroup.setGeometry(QtCore.QRect(10, 50, 761, 430))
        self.tabWidgetGroup.setObjectName("tabWidgetGroup")
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.tabWidgetGroup.addTab(self.tabGeneral, "")
        self.tabStyle1 = QtGui.QWidget()
        self.tabStyle1.setObjectName("tabStyle1")
        self.tabWidgetGroup.addTab(self.tabStyle1, "")
        self.tabTex1 = QtGui.QWidget()
        self.tabTex1.setObjectName("tabTex1")
        self.tabWidgetGroup.addTab(self.tabTex1, "")
        self.tabHyphenation = QtGui.QWidget()
        self.tabHyphenation.setObjectName("tabHyphenation")
        self.tabWidgetGroup.addTab(self.tabHyphenation, "")
        self.label_8 = QtGui.QLabel(self.pageGroup)
        self.label_8.setGeometry(QtCore.QRect(40, 480, 131, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.pageGroup)
        self.label_9.setGeometry(QtCore.QRect(640, 480, 66, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.pageGroup)
        self.label_10.setGeometry(QtCore.QRect(230, 480, 131, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.pageGroup)
        self.label_11.setGeometry(QtCore.QRect(410, 480, 150, 31))
        self.label_11.setObjectName("label_11")
        self.toolButtonGroupDraft = QtGui.QToolButton(self.pageGroup)
        self.toolButtonGroupDraft.setGeometry(QtCore.QRect(632, 10, 40, 35))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/document_draft-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGroupDraft.setIcon(icon3)
        self.toolButtonGroupDraft.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonGroupDraft.setObjectName("toolButtonGroupDraft")
        self.toolButtonGroupProof = QtGui.QToolButton(self.pageGroup)
        self.toolButtonGroupProof.setGeometry(QtCore.QRect(682, 10, 40, 35))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/document_proof-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGroupProof.setIcon(icon4)
        self.toolButtonGroupProof.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonGroupProof.setObjectName("toolButtonGroupProof")
        self.toolButtonGroupFinal = QtGui.QToolButton(self.pageGroup)
        self.toolButtonGroupFinal.setGeometry(QtCore.QRect(732, 10, 40, 35))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/document_final-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGroupFinal.setIcon(icon5)
        self.toolButtonGroupFinal.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonGroupFinal.setObjectName("toolButtonGroupFinal")
        self.toolButtonGroupSelect = QtGui.QToolButton(self.pageGroup)
        self.toolButtonGroupSelect.setGeometry(QtCore.QRect(582, 10, 40, 35))
        self.toolButtonGroupSelect.setMinimumSize(QtCore.QSize(0, 6))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Gnome-Document-Open-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGroupSelect.setIcon(icon6)
        self.toolButtonGroupSelect.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonGroupSelect.setObjectName("toolButtonGroupSelect")
        self.stackedWidgetWorkArea.addWidget(self.pageGroup)
        self.pageComponent = QtGui.QWidget()
        self.pageComponent.setObjectName("pageComponent")
        self.labelComponentCid = QtGui.QLabel(self.pageComponent)
        self.labelComponentCid.setGeometry(QtCore.QRect(110, 10, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelComponentCid.setFont(font)
        self.labelComponentCid.setObjectName("labelComponentCid")
        self.labelComponentComponent = QtGui.QLabel(self.pageComponent)
        self.labelComponentComponent.setGeometry(QtCore.QRect(10, 10, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelComponentComponent.setFont(font)
        self.labelComponentComponent.setObjectName("labelComponentComponent")
        self.tabWidgetComponent = QtGui.QTabWidget(self.pageComponent)
        self.tabWidgetComponent.setGeometry(QtCore.QRect(10, 50, 762, 430))
        self.tabWidgetComponent.setObjectName("tabWidgetComponent")
        self.tabWorking = QtGui.QWidget()
        self.tabWorking.setObjectName("tabWorking")
        self.plainTextEditComponentWorking = QtGui.QPlainTextEdit(self.tabWorking)
        self.plainTextEditComponentWorking.setGeometry(QtCore.QRect(20, 10, 721, 371))
        self.plainTextEditComponentWorking.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.plainTextEditComponentWorking.setObjectName("plainTextEditComponentWorking")
        self.tabWidgetComponent.addTab(self.tabWorking, "")
        self.tabSource = QtGui.QWidget()
        self.tabSource.setObjectName("tabSource")
        self.tabWidgetComponent.addTab(self.tabSource, "")
        self.tabIllustration = QtGui.QWidget()
        self.tabIllustration.setObjectName("tabIllustration")
        self.tabWidgetComponent.addTab(self.tabIllustration, "")
        self.label_12 = QtGui.QLabel(self.pageComponent)
        self.label_12.setGeometry(QtCore.QRect(490, 510, 131, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.pageComponent)
        self.label_13.setGeometry(QtCore.QRect(1090, 510, 66, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.pageComponent)
        self.label_14.setGeometry(QtCore.QRect(680, 510, 131, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.pageComponent)
        self.label_15.setGeometry(QtCore.QRect(870, 510, 131, 31))
        self.label_15.setObjectName("label_15")
        self.label_19 = QtGui.QLabel(self.pageComponent)
        self.label_19.setGeometry(QtCore.QRect(410, 480, 150, 31))
        self.label_19.setObjectName("label_19")
        self.label_16 = QtGui.QLabel(self.pageComponent)
        self.label_16.setGeometry(QtCore.QRect(40, 480, 131, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.pageComponent)
        self.label_17.setGeometry(QtCore.QRect(640, 480, 66, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.pageComponent)
        self.label_18.setGeometry(QtCore.QRect(230, 480, 131, 31))
        self.label_18.setObjectName("label_18")
        self.toolButton_4 = QtGui.QToolButton(self.pageComponent)
        self.toolButton_4.setGeometry(QtCore.QRect(632, 10, 40, 35))
        self.toolButton_4.setIcon(icon3)
        self.toolButton_4.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtGui.QToolButton(self.pageComponent)
        self.toolButton_5.setGeometry(QtCore.QRect(732, 10, 40, 35))
        self.toolButton_5.setIcon(icon5)
        self.toolButton_5.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtGui.QToolButton(self.pageComponent)
        self.toolButton_6.setGeometry(QtCore.QRect(682, 10, 40, 35))
        self.toolButton_6.setIcon(icon4)
        self.toolButton_6.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButtonComponentSelect = QtGui.QToolButton(self.pageComponent)
        self.toolButtonComponentSelect.setGeometry(QtCore.QRect(582, 10, 40, 35))
        self.toolButtonComponentSelect.setIcon(icon6)
        self.toolButtonComponentSelect.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonComponentSelect.setObjectName("toolButtonComponentSelect")
        self.stackedWidgetWorkArea.addWidget(self.pageComponent)
        self.pageFont = QtGui.QWidget()
        self.pageFont.setObjectName("pageFont")
        self.tabWidgetFont = QtGui.QTabWidget(self.pageFont)
        self.tabWidgetFont.setGeometry(QtCore.QRect(10, 50, 762, 430))
        self.tabWidgetFont.setObjectName("tabWidgetFont")
        self.tabGeneralSettings1 = QtGui.QWidget()
        self.tabGeneralSettings1.setObjectName("tabGeneralSettings1")
        self.tabWidgetFont.addTab(self.tabGeneralSettings1, "")
        self.tab_unused = QtGui.QWidget()
        self.tab_unused.setObjectName("tab_unused")
        self.tabWidgetFont.addTab(self.tab_unused, "")
        self.label_21 = QtGui.QLabel(self.pageFont)
        self.label_21.setGeometry(QtCore.QRect(640, 480, 66, 31))
        self.label_21.setObjectName("label_21")
        self.label_23 = QtGui.QLabel(self.pageFont)
        self.label_23.setGeometry(QtCore.QRect(410, 480, 150, 31))
        self.label_23.setObjectName("label_23")
        self.label_22 = QtGui.QLabel(self.pageFont)
        self.label_22.setGeometry(QtCore.QRect(230, 480, 131, 31))
        self.label_22.setObjectName("label_22")
        self.label_20 = QtGui.QLabel(self.pageFont)
        self.label_20.setGeometry(QtCore.QRect(40, 480, 131, 31))
        self.label_20.setObjectName("label_20")
        self.stackedWidgetWorkArea.addWidget(self.pageFont)
        self.horizontalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(10, 560, 781, 16))
        self.horizontalScrollBar.setMinimum(0)
        self.horizontalScrollBar.setMaximum(3)
        self.horizontalScrollBar.setSingleStep(1)
        self.horizontalScrollBar.setPageStep(1)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.toolButtonSelectProject = QtGui.QToolButton(self.centralwidget)
        self.toolButtonSelectProject.setGeometry(QtCore.QRect(20, 5, 35, 30))
        self.toolButtonSelectProject.setIcon(icon6)
        self.toolButtonSelectProject.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonSelectProject.setObjectName("toolButtonSelectProject")
        self.toolButtonSystemPreferences = QtGui.QToolButton(self.centralwidget)
        self.toolButtonSystemPreferences.setGeometry(QtCore.QRect(70, 5, 35, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Gnome-Preferences-System-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonSystemPreferences.setIcon(icon7)
        self.toolButtonSystemPreferences.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonSystemPreferences.setObjectName("toolButtonSystemPreferences")
        self.toolButtonQuit = QtGui.QToolButton(self.centralwidget)
        self.toolButtonQuit.setGeometry(QtCore.QRect(747, 5, 35, 30))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Gnome-Application-Exit-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonQuit.setIcon(icon8)
        self.toolButtonQuit.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonQuit.setObjectName("toolButtonQuit")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 30, 762, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 25))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuGroup = QtGui.QMenu(self.menubar)
        self.menuGroup.setObjectName("menuGroup")
        self.menuComponent = QtGui.QMenu(self.menubar)
        self.menuComponent.setObjectName("menuComponent")
        self.menuFont = QtGui.QMenu(self.menubar)
        self.menuFont.setObjectName("menuFont")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuProjectSelect = QtGui.QAction(MainWindow)
        self.menuProjectSelect.setObjectName("menuProjectSelect")
        self.menuProjectAdd = QtGui.QAction(MainWindow)
        self.menuProjectAdd.setObjectName("menuProjectAdd")
        self.menuProjectQuit = QtGui.QAction(MainWindow)
        self.menuProjectQuit.setObjectName("menuProjectQuit")
        self.menuHelpAbout = QtGui.QAction(MainWindow)
        self.menuHelpAbout.setObjectName("menuHelpAbout")
        self.menuProjectSystempreferences = QtGui.QAction(MainWindow)
        self.menuProjectSystempreferences.setObjectName("menuProjectSystempreferences")
        self.menuHelpHelp = QtGui.QAction(MainWindow)
        self.menuHelpHelp.setObjectName("menuHelpHelp")
        self.menuProjectBackup = QtGui.QAction(MainWindow)
        self.menuProjectBackup.setObjectName("menuProjectBackup")
        self.menuProjectArchive = QtGui.QAction(MainWindow)
        self.menuProjectArchive.setObjectName("menuProjectArchive")
        self.menuProjectRemove = QtGui.QAction(MainWindow)
        self.menuProjectRemove.setObjectName("menuProjectRemove")
        self.menuProjectReap = QtGui.QAction(MainWindow)
        self.menuProjectReap.setObjectName("menuProjectReap")
        self.menuProjectTemplate = QtGui.QAction(MainWindow)
        self.menuProjectTemplate.setObjectName("menuProjectTemplate")
        self.menuComponentAdd = QtGui.QAction(MainWindow)
        self.menuComponentAdd.setObjectName("menuComponentAdd")
        self.menuComponentRemove = QtGui.QAction(MainWindow)
        self.menuComponentRemove.setObjectName("menuComponentRemove")
        self.menuComponentSelect = QtGui.QAction(MainWindow)
        self.menuComponentSelect.setObjectName("menuComponentSelect")
        self.menuGroupAdd = QtGui.QAction(MainWindow)
        self.menuGroupAdd.setObjectName("menuGroupAdd")
        self.menuGroupRemove = QtGui.QAction(MainWindow)
        self.menuGroupRemove.setObjectName("menuGroupRemove")
        self.menuGroupSelect = QtGui.QAction(MainWindow)
        self.menuGroupSelect.setObjectName("menuGroupSelect")
        self.menuProjectRestore = QtGui.QAction(MainWindow)
        self.menuProjectRestore.setObjectName("menuProjectRestore")
        self.menuProjectBind = QtGui.QAction(MainWindow)
        self.menuProjectBind.setObjectName("menuProjectBind")
        self.menuProjectCloud = QtGui.QAction(MainWindow)
        self.menuProjectCloud.setObjectName("menuProjectCloud")
        self.menuHelpExamples = QtGui.QAction(MainWindow)
        self.menuHelpExamples.setObjectName("menuHelpExamples")
        self.menuGroupUpdate = QtGui.QAction(MainWindow)
        self.menuGroupUpdate.setObjectName("menuGroupUpdate")
        self.menuComponentUpdate = QtGui.QAction(MainWindow)
        self.menuComponentUpdate.setObjectName("menuComponentUpdate")
        self.menuProjectUpdate = QtGui.QAction(MainWindow)
        self.menuProjectUpdate.setObjectName("menuProjectUpdate")
        self.actionDraft = QtGui.QAction(MainWindow)
        self.actionDraft.setObjectName("actionDraft")
        self.actionFinal = QtGui.QAction(MainWindow)
        self.actionFinal.setObjectName("actionFinal")
        self.actionProof = QtGui.QAction(MainWindow)
        self.actionProof.setObjectName("actionProof")
        self.actionDraft_2 = QtGui.QAction(MainWindow)
        self.actionDraft_2.setObjectName("actionDraft_2")
        self.actionFinal_2 = QtGui.QAction(MainWindow)
        self.actionFinal_2.setObjectName("actionFinal_2")
        self.actionProof_2 = QtGui.QAction(MainWindow)
        self.actionProof_2.setObjectName("actionProof_2")
        self.menuProjectEdit = QtGui.QAction(MainWindow)
        self.menuProjectEdit.setObjectName("menuProjectEdit")
        self.menuGroupEdit = QtGui.QAction(MainWindow)
        self.menuGroupEdit.setObjectName("menuGroupEdit")
        self.menuComponentEdit = QtGui.QAction(MainWindow)
        self.menuComponentEdit.setObjectName("menuComponentEdit")
        self.menuFontAdd = QtGui.QAction(MainWindow)
        self.menuFontAdd.setObjectName("menuFontAdd")
        self.menuFontRemove = QtGui.QAction(MainWindow)
        self.menuFontRemove.setObjectName("menuFontRemove")
        self.menuFontUpdate = QtGui.QAction(MainWindow)
        self.menuFontUpdate.setObjectName("menuFontUpdate")
        self.menuToolsMockup = QtGui.QAction(MainWindow)
        self.menuToolsMockup.setObjectName("menuToolsMockup")
        self.menuToolsIndextabs = QtGui.QAction(MainWindow)
        self.menuToolsIndextabs.setObjectName("menuToolsIndextabs")
        self.menuProject.addAction(self.menuProjectAdd)
        self.menuProject.addAction(self.menuProjectRemove)
        self.menuProject.addAction(self.menuProjectSelect)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.menuProjectArchive)
        self.menuProject.addAction(self.menuProjectCloud)
        self.menuProject.addAction(self.menuProjectBackup)
        self.menuProject.addAction(self.menuProjectBind)
        self.menuProject.addAction(self.menuProjectReap)
        self.menuProject.addAction(self.menuProjectTemplate)
        self.menuProject.addAction(self.menuProjectUpdate)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.menuProjectSystempreferences)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.menuProjectQuit)
        self.menuHelp.addAction(self.menuHelpHelp)
        self.menuHelp.addAction(self.menuHelpExamples)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.menuHelpAbout)
        self.menuGroup.addAction(self.menuGroupAdd)
        self.menuGroup.addAction(self.menuGroupRemove)
        self.menuGroup.addAction(self.menuGroupSelect)
        self.menuGroup.addAction(self.menuGroupUpdate)
        self.menuGroup.addSeparator()
        self.menuGroup.addAction(self.actionDraft)
        self.menuGroup.addAction(self.actionFinal)
        self.menuGroup.addAction(self.actionProof)
        self.menuComponent.addAction(self.menuComponentAdd)
        self.menuComponent.addAction(self.menuComponentRemove)
        self.menuComponent.addAction(self.menuComponentSelect)
        self.menuComponent.addAction(self.menuComponentUpdate)
        self.menuComponent.addSeparator()
        self.menuComponent.addAction(self.actionDraft_2)
        self.menuComponent.addAction(self.actionFinal_2)
        self.menuComponent.addAction(self.actionProof_2)
        self.menuFont.addAction(self.menuFontAdd)
        self.menuFont.addAction(self.menuFontRemove)
        self.menuFont.addAction(self.menuFontUpdate)
        self.menuTools.addAction(self.menuToolsMockup)
        self.menuTools.addAction(self.menuToolsIndextabs)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuGroup.menuAction())
        self.menubar.addAction(self.menuComponent.menuAction())
        self.menubar.addAction(self.menuFont.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidgetWorkArea.setCurrentIndex(2)
        self.tabWidgetProject.setCurrentIndex(0)
        self.tabWidgetGroup.setCurrentIndex(3)
        self.tabWidgetComponent.setCurrentIndex(0)
        self.tabWidgetFont.setCurrentIndex(1)
        QtCore.QObject.connect(self.horizontalScrollBar, QtCore.SIGNAL("sliderMoved(int)"), self.stackedWidgetWorkArea.setCurrentIndex)
        QtCore.QObject.connect(self.toolButtonSelectProject, QtCore.SIGNAL("clicked()"), MainWindow.update)
        QtCore.QObject.connect(self.toolButtonQuit, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.toolButtonSystemPreferences, QtCore.SIGNAL("clicked()"), MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Rapuma", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProjectPid.setText(QtGui.QApplication.translate("MainWindow", "Project ID", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProjectProject.setText(QtGui.QApplication.translate("MainWindow", "Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00aa7f;\">Project</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditProjectName.setToolTip(QtGui.QApplication.translate("MainWindow", "Project name, could be book title", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditProjectName.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabGeneralSettings), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabToolTip(self.tabWidgetProject.indexOf(self.tabGeneralSettings), QtGui.QApplication.translate("MainWindow", "Backup project", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabStyle), QtGui.QApplication.translate("MainWindow", "Style", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabTex), QtGui.QApplication.translate("MainWindow", "TeX", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Group</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Component</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Font</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Backup project", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Update cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setToolTip(QtGui.QApplication.translate("MainWindow", "Bind project", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGroup.setText(QtGui.QApplication.translate("MainWindow", "Group:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGroupGid.setText(QtGui.QApplication.translate("MainWindow", "Group ID", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetGroup.setTabText(self.tabWidgetGroup.indexOf(self.tabGeneral), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetGroup.setTabText(self.tabWidgetGroup.indexOf(self.tabStyle1), QtGui.QApplication.translate("MainWindow", "Style", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetGroup.setTabText(self.tabWidgetGroup.indexOf(self.tabTex1), QtGui.QApplication.translate("MainWindow", "TeX", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetGroup.setTabText(self.tabWidgetGroup.indexOf(self.tabHyphenation), QtGui.QApplication.translate("MainWindow", "Hyphenation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Project</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Font</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00aa7f;\">Group</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Component</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGroupDraft.setToolTip(QtGui.QApplication.translate("MainWindow", "Produce a draft PDF of this group", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGroupDraft.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGroupProof.setToolTip(QtGui.QApplication.translate("MainWindow", "Produce a proof PDF of this group", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGroupProof.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGroupFinal.setToolTip(QtGui.QApplication.translate("MainWindow", "Produce a final PDF of this group", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGroupFinal.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGroupSelect.setToolTip(QtGui.QApplication.translate("MainWindow", "Select a group to work on", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonGroupSelect.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComponentCid.setText(QtGui.QApplication.translate("MainWindow", "Comp ID", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComponentComponent.setText(QtGui.QApplication.translate("MainWindow", "Component:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetComponent.setTabText(self.tabWidgetComponent.indexOf(self.tabWorking), QtGui.QApplication.translate("MainWindow", "Working", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetComponent.setTabText(self.tabWidgetComponent.indexOf(self.tabSource), QtGui.QApplication.translate("MainWindow", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetComponent.setTabText(self.tabWidgetComponent.indexOf(self.tabIllustration), QtGui.QApplication.translate("MainWindow", "Illustration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline;\">Project</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Font</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Group</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Component</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00aa7f;\">Component</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Project</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Font</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Group</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_4.setToolTip(QtGui.QApplication.translate("MainWindow", "Produce a draft PDF of this component", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_4.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setToolTip(QtGui.QApplication.translate("MainWindow", "Produce a final PDF version of this component", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_6.setToolTip(QtGui.QApplication.translate("MainWindow", "Produce a proof PDF of this component", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_6.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonComponentSelect.setToolTip(QtGui.QApplication.translate("MainWindow", "Select a component to work on", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonComponentSelect.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetFont.setTabText(self.tabWidgetFont.indexOf(self.tabGeneralSettings1), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetFont.setTabText(self.tabWidgetFont.indexOf(self.tab_unused), QtGui.QApplication.translate("MainWindow", "Unused", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00aa7f;\">Font</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Component</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Group</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#cfcfcf;\">Project</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonSelectProject.setToolTip(QtGui.QApplication.translate("MainWindow", "Select a project", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonSelectProject.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonSystemPreferences.setToolTip(QtGui.QApplication.translate("MainWindow", "Adjust Rapuma system settings", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonSystemPreferences.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonQuit.setToolTip(QtGui.QApplication.translate("MainWindow", "Exit Rapuma", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonQuit.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProject.setTitle(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Group", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponent.setTitle(QtGui.QApplication.translate("MainWindow", "Component", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFont.setTitle(QtGui.QApplication.translate("MainWindow", "Font", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "open", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectSelect.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectSelect.setToolTip(QtGui.QApplication.translate("MainWindow", "Open an exsiting project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectAdd.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "Create a new Rapuma project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectQuit.setToolTip(QtGui.QApplication.translate("MainWindow", "Quit Rapuma", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelpAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelpAbout.setToolTip(QtGui.QApplication.translate("MainWindow", "Learn about what Rapuma is", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectSystempreferences.setText(QtGui.QApplication.translate("MainWindow", "System Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectSystempreferences.setToolTip(QtGui.QApplication.translate("MainWindow", "Change Rapuma system preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelpHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelpHelp.setToolTip(QtGui.QApplication.translate("MainWindow", "Find information about how to use Rapuma", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectBackup.setText(QtGui.QApplication.translate("MainWindow", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectBackup.setToolTip(QtGui.QApplication.translate("MainWindow", "Backup an existing project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectArchive.setText(QtGui.QApplication.translate("MainWindow", "Archive", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectArchive.setToolTip(QtGui.QApplication.translate("MainWindow", "Archive an existing project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectRemove.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectRemove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove an existing project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectReap.setText(QtGui.QApplication.translate("MainWindow", "REAP", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectReap.setToolTip(QtGui.QApplication.translate("MainWindow", "Add a project to SIL REAP (Archive)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectTemplate.setText(QtGui.QApplication.translate("MainWindow", "Template", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponentAdd.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponentAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "Add a component to the selected group", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponentRemove.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponentRemove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove a component from the selected group", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponentSelect.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponentSelect.setToolTip(QtGui.QApplication.translate("MainWindow", "Select a component(s) to render ", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGroupAdd.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGroupAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "Add a group to this project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGroupRemove.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGroupRemove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove a group from this project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGroupSelect.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGroupSelect.setToolTip(QtGui.QApplication.translate("MainWindow", "Select a group to process in this project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectRestore.setText(QtGui.QApplication.translate("MainWindow", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectRestore.setToolTip(QtGui.QApplication.translate("MainWindow", "Restore a Rapuma project from backup or archive", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectBind.setText(QtGui.QApplication.translate("MainWindow", "Bind", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectBind.setToolTip(QtGui.QApplication.translate("MainWindow", "Bind groups in the main content section", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectCloud.setText(QtGui.QApplication.translate("MainWindow", "Cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectCloud.setToolTip(QtGui.QApplication.translate("MainWindow", "Save the current project to the cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelpExamples.setText(QtGui.QApplication.translate("MainWindow", "Examples", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelpExamples.setToolTip(QtGui.QApplication.translate("MainWindow", "Try a couple Rapuma project examples", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGroupUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGroupUpdate.setToolTip(QtGui.QApplication.translate("MainWindow", "Update a group(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponentUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponentUpdate.setToolTip(QtGui.QApplication.translate("MainWindow", "Update a component(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectUpdate.setToolTip(QtGui.QApplication.translate("MainWindow", "Update project elements", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDraft.setText(QtGui.QApplication.translate("MainWindow", "Draft", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFinal.setText(QtGui.QApplication.translate("MainWindow", "Final", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProof.setText(QtGui.QApplication.translate("MainWindow", "Proof", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDraft_2.setText(QtGui.QApplication.translate("MainWindow", "Draft", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFinal_2.setText(QtGui.QApplication.translate("MainWindow", "Final", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProof_2.setText(QtGui.QApplication.translate("MainWindow", "Proof", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectEdit.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjectEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Edit settings or render the current project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGroupEdit.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGroupEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Edit settings or render the current group", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponentEdit.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponentEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Edit settings or render the current component", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFontAdd.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFontAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "Add a font to this project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFontRemove.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFontRemove.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove a font from this project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFontUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFontUpdate.setToolTip(QtGui.QApplication.translate("MainWindow", "Update a font for this project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuToolsMockup.setText(QtGui.QApplication.translate("MainWindow", "Mockup", None, QtGui.QApplication.UnicodeUTF8))
        self.menuToolsMockup.setToolTip(QtGui.QApplication.translate("MainWindow", "Create a mockup (print dummy) of the full publication", None, QtGui.QApplication.UnicodeUTF8))
        self.menuToolsIndextabs.setText(QtGui.QApplication.translate("MainWindow", "Index Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.menuToolsIndextabs.setToolTip(QtGui.QApplication.translate("MainWindow", "Create index page tabs on the main content", None, QtGui.QApplication.UnicodeUTF8))

from . import pyresources_rc
