# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dennis/Projects/rapuma/lib/rapuma/dialog/menu_project_cloud_dlg.ui'
#
# Created: Wed Feb 12 21:02:20 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MenuProjectCloud(object):
    def setupUi(self, MenuProjectCloud):
        MenuProjectCloud.setObjectName("MenuProjectCloud")
        MenuProjectCloud.resize(448, 277)
        self.gridLayout_2 = QtGui.QGridLayout(MenuProjectCloud)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelPathLocal = QtGui.QLabel(MenuProjectCloud)
        self.labelPathLocal.setObjectName("labelPathLocal")
        self.gridLayout_2.addWidget(self.labelPathLocal, 0, 0, 1, 1)
        self.lineEditProjectLocal = QtGui.QLineEdit(MenuProjectCloud)
        self.lineEditProjectLocal.setObjectName("lineEditProjectLocal")
        self.gridLayout_2.addWidget(self.lineEditProjectLocal, 1, 0, 1, 3)
        self.pushButtonLocalBrowse = QtGui.QPushButton(MenuProjectCloud)
        self.pushButtonLocalBrowse.setObjectName("pushButtonLocalBrowse")
        self.gridLayout_2.addWidget(self.pushButtonLocalBrowse, 1, 3, 1, 1)
        self.labelPathCloud = QtGui.QLabel(MenuProjectCloud)
        self.labelPathCloud.setObjectName("labelPathCloud")
        self.gridLayout_2.addWidget(self.labelPathCloud, 2, 0, 1, 1)
        self.lineEditProjectCloud = QtGui.QLineEdit(MenuProjectCloud)
        self.lineEditProjectCloud.setObjectName("lineEditProjectCloud")
        self.gridLayout_2.addWidget(self.lineEditProjectCloud, 3, 0, 1, 3)
        self.pushButtonCloudBrowse = QtGui.QPushButton(MenuProjectCloud)
        self.pushButtonCloudBrowse.setObjectName("pushButtonCloudBrowse")
        self.gridLayout_2.addWidget(self.pushButtonCloudBrowse, 3, 3, 1, 1)
        self.groupBoxAction = QtGui.QGroupBox(MenuProjectCloud)
        self.groupBoxAction.setObjectName("groupBoxAction")
        self.gridLayout = QtGui.QGridLayout(self.groupBoxAction)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButtonPush = QtGui.QRadioButton(self.groupBoxAction)
        self.radioButtonPush.setChecked(True)
        self.radioButtonPush.setObjectName("radioButtonPush")
        self.gridLayout.addWidget(self.radioButtonPush, 0, 0, 1, 1)
        self.radioButtonPull = QtGui.QRadioButton(self.groupBoxAction)
        self.radioButtonPull.setObjectName("radioButtonPull")
        self.gridLayout.addWidget(self.radioButtonPull, 1, 0, 1, 1)
        self.radioButtonRestore = QtGui.QRadioButton(self.groupBoxAction)
        self.radioButtonRestore.setObjectName("radioButtonRestore")
        self.gridLayout.addWidget(self.radioButtonRestore, 2, 0, 1, 1)
        self.checkBoxFlush = QtGui.QCheckBox(self.groupBoxAction)
        self.checkBoxFlush.setEnabled(True)
        self.checkBoxFlush.setObjectName("checkBoxFlush")
        self.gridLayout.addWidget(self.checkBoxFlush, 0, 1, 1, 1)
        self.checkBoxBackup = QtGui.QCheckBox(self.groupBoxAction)
        self.checkBoxBackup.setEnabled(False)
        self.checkBoxBackup.setChecked(True)
        self.checkBoxBackup.setObjectName("checkBoxBackup")
        self.gridLayout.addWidget(self.checkBoxBackup, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxAction, 4, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.pushButtonOk = QtGui.QPushButton(MenuProjectCloud)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.gridLayout_2.addWidget(self.pushButtonOk, 5, 1, 1, 1)
        self.pushButtonCancel = QtGui.QPushButton(MenuProjectCloud)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_2.addWidget(self.pushButtonCancel, 5, 2, 1, 2)

        self.retranslateUi(MenuProjectCloud)
        QtCore.QObject.connect(self.pushButtonCancel, QtCore.SIGNAL("clicked(bool)"), MenuProjectCloud.close)
        QtCore.QObject.connect(self.pushButtonOk, QtCore.SIGNAL("clicked()"), MenuProjectCloud.setupUi)
        QtCore.QObject.connect(self.radioButtonPull, QtCore.SIGNAL("toggled(bool)"), self.checkBoxBackup.setEnabled)
        QtCore.QObject.connect(self.radioButtonPush, QtCore.SIGNAL("toggled(bool)"), self.checkBoxFlush.setEnabled)
        QtCore.QObject.connect(self.pushButtonLocalBrowse, QtCore.SIGNAL("clicked(bool)"), MenuProjectCloud.setupUi)
        QtCore.QObject.connect(self.pushButtonCloudBrowse, QtCore.SIGNAL("clicked(bool)"), MenuProjectCloud.setupUi)
        QtCore.QMetaObject.connectSlotsByName(MenuProjectCloud)
        MenuProjectCloud.setTabOrder(self.pushButtonCancel, self.pushButtonOk)
        MenuProjectCloud.setTabOrder(self.pushButtonOk, self.lineEditProjectLocal)
        MenuProjectCloud.setTabOrder(self.lineEditProjectLocal, self.pushButtonLocalBrowse)
        MenuProjectCloud.setTabOrder(self.pushButtonLocalBrowse, self.lineEditProjectCloud)
        MenuProjectCloud.setTabOrder(self.lineEditProjectCloud, self.pushButtonCloudBrowse)
        MenuProjectCloud.setTabOrder(self.pushButtonCloudBrowse, self.radioButtonPush)
        MenuProjectCloud.setTabOrder(self.radioButtonPush, self.radioButtonPull)
        MenuProjectCloud.setTabOrder(self.radioButtonPull, self.radioButtonRestore)
        MenuProjectCloud.setTabOrder(self.radioButtonRestore, self.checkBoxFlush)
        MenuProjectCloud.setTabOrder(self.checkBoxFlush, self.checkBoxBackup)

    def retranslateUi(self, MenuProjectCloud):
        MenuProjectCloud.setWindowTitle(QtGui.QApplication.translate("MenuProjectCloud", "Rapuma - Manage Cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPathLocal.setText(QtGui.QApplication.translate("MenuProjectCloud", "Path to Local Project", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditProjectLocal.setToolTip(QtGui.QApplication.translate("MenuProjectCloud", "Enter the path to the local project", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditProjectLocal.setPlaceholderText(QtGui.QApplication.translate("MenuProjectCloud", "Enter Path", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLocalBrowse.setToolTip(QtGui.QApplication.translate("MenuProjectCloud", "Browse to an existing local project", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLocalBrowse.setText(QtGui.QApplication.translate("MenuProjectCloud", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPathCloud.setText(QtGui.QApplication.translate("MenuProjectCloud", "Path to Cloud Project", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditProjectCloud.setToolTip(QtGui.QApplication.translate("MenuProjectCloud", "Enter the path to the cloud project", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditProjectCloud.setPlaceholderText(QtGui.QApplication.translate("MenuProjectCloud", "Enter Path", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCloudBrowse.setToolTip(QtGui.QApplication.translate("MenuProjectCloud", "Browse to a project in the cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCloudBrowse.setText(QtGui.QApplication.translate("MenuProjectCloud", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxAction.setToolTip(QtGui.QApplication.translate("MenuProjectCloud", "Define the action to be taken", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxAction.setTitle(QtGui.QApplication.translate("MenuProjectCloud", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonPush.setToolTip(QtGui.QApplication.translate("MenuProjectCloud", "Update (push to) the cloud with local project data", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonPush.setText(QtGui.QApplication.translate("MenuProjectCloud", "Local to Cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonPull.setToolTip(QtGui.QApplication.translate("MenuProjectCloud", "Update the local project with data pulled from the cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonPull.setText(QtGui.QApplication.translate("MenuProjectCloud", "Cloud to Local", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRestore.setToolTip(QtGui.QApplication.translate("MenuProjectCloud", "Add a new local project with data from the cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRestore.setText(QtGui.QApplication.translate("MenuProjectCloud", "Restore From Cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxFlush.setToolTip(QtGui.QApplication.translate("MenuProjectCloud", "Completly replace the cloud version with the local version", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxFlush.setText(QtGui.QApplication.translate("MenuProjectCloud", "Flush", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxBackup.setToolTip(QtGui.QApplication.translate("MenuProjectCloud", "Create a backup of the project before replacing it with cloud version", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxBackup.setText(QtGui.QApplication.translate("MenuProjectCloud", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOk.setToolTip(QtGui.QApplication.translate("MenuProjectCloud", "Remove a selected project", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOk.setText(QtGui.QApplication.translate("MenuProjectCloud", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("MenuProjectCloud", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

