# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dennis/Projects/rapuma/lib/rapuma/dialog/menu_project_backup_dlg.ui'
#
# Created: Thu Feb 27 16:46:26 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MenuProjectBackup(object):
    def setupUi(self, MenuProjectBackup):
        MenuProjectBackup.setObjectName("MenuProjectBackup")
        MenuProjectBackup.resize(370, 417)
        self.gridLayout_2 = QtGui.QGridLayout(MenuProjectBackup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelSelectProject = QtGui.QLabel(MenuProjectBackup)
        self.labelSelectProject.setObjectName("labelSelectProject")
        self.gridLayout_2.addWidget(self.labelSelectProject, 0, 0, 1, 1)
        self.labelSelectBackup = QtGui.QLabel(MenuProjectBackup)
        self.labelSelectBackup.setObjectName("labelSelectBackup")
        self.gridLayout_2.addWidget(self.labelSelectBackup, 2, 0, 1, 1)
        self.groupBoxBackupAction = QtGui.QGroupBox(MenuProjectBackup)
        self.groupBoxBackupAction.setObjectName("groupBoxBackupAction")
        self.gridLayout = QtGui.QGridLayout(self.groupBoxBackupAction)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButtonBackup = QtGui.QRadioButton(self.groupBoxBackupAction)
        self.radioButtonBackup.setChecked(True)
        self.radioButtonBackup.setObjectName("radioButtonBackup")
        self.gridLayout.addWidget(self.radioButtonBackup, 0, 0, 1, 1)
        self.radioButtonRestore = QtGui.QRadioButton(self.groupBoxBackupAction)
        self.radioButtonRestore.setChecked(False)
        self.radioButtonRestore.setObjectName("radioButtonRestore")
        self.gridLayout.addWidget(self.radioButtonRestore, 1, 0, 1, 1)
        self.radioButtonRemove = QtGui.QRadioButton(self.groupBoxBackupAction)
        self.radioButtonRemove.setObjectName("radioButtonRemove")
        self.gridLayout.addWidget(self.radioButtonRemove, 2, 0, 1, 1)
        self.radioButtonRestoreNew = QtGui.QRadioButton(self.groupBoxBackupAction)
        self.radioButtonRestoreNew.setObjectName("radioButtonRestoreNew")
        self.gridLayout.addWidget(self.radioButtonRestoreNew, 3, 0, 1, 1)
        self.checkBoxCustomBackupLocation = QtGui.QCheckBox(self.groupBoxBackupAction)
        self.checkBoxCustomBackupLocation.setEnabled(False)
        self.checkBoxCustomBackupLocation.setChecked(False)
        self.checkBoxCustomBackupLocation.setObjectName("checkBoxCustomBackupLocation")
        self.gridLayout.addWidget(self.checkBoxCustomBackupLocation, 3, 1, 1, 1)
        self.labelNeLocation = QtGui.QLabel(self.groupBoxBackupAction)
        self.labelNeLocation.setEnabled(False)
        self.labelNeLocation.setObjectName("labelNeLocation")
        self.gridLayout.addWidget(self.labelNeLocation, 4, 0, 1, 1)
        self.pushButtonBrowseProjectLocation = QtGui.QPushButton(self.groupBoxBackupAction)
        self.pushButtonBrowseProjectLocation.setEnabled(False)
        self.pushButtonBrowseProjectLocation.setObjectName("pushButtonBrowseProjectLocation")
        self.gridLayout.addWidget(self.pushButtonBrowseProjectLocation, 5, 2, 1, 1)
        self.labelBackupFile = QtGui.QLabel(self.groupBoxBackupAction)
        self.labelBackupFile.setEnabled(False)
        self.labelBackupFile.setObjectName("labelBackupFile")
        self.gridLayout.addWidget(self.labelBackupFile, 6, 0, 1, 1)
        self.pushButtonBrowseBackupFile = QtGui.QPushButton(self.groupBoxBackupAction)
        self.pushButtonBrowseBackupFile.setEnabled(False)
        self.pushButtonBrowseBackupFile.setObjectName("pushButtonBrowseBackupFile")
        self.gridLayout.addWidget(self.pushButtonBrowseBackupFile, 7, 2, 1, 1)
        self.lineEditProjectLocation = QtGui.QLineEdit(self.groupBoxBackupAction)
        self.lineEditProjectLocation.setEnabled(False)
        self.lineEditProjectLocation.setObjectName("lineEditProjectLocation")
        self.gridLayout.addWidget(self.lineEditProjectLocation, 5, 0, 1, 2)
        self.lineEditBackupFile = QtGui.QLineEdit(self.groupBoxBackupAction)
        self.lineEditBackupFile.setEnabled(False)
        self.lineEditBackupFile.setObjectName("lineEditBackupFile")
        self.gridLayout.addWidget(self.lineEditBackupFile, 7, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBoxBackupAction, 4, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.pushButtonOk = QtGui.QPushButton(MenuProjectBackup)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.gridLayout_2.addWidget(self.pushButtonOk, 5, 1, 1, 1)
        self.pushButtonCancel = QtGui.QPushButton(MenuProjectBackup)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_2.addWidget(self.pushButtonCancel, 5, 2, 1, 1)
        self.comboBoxSelectProject = QtGui.QComboBox(MenuProjectBackup)
        self.comboBoxSelectProject.setObjectName("comboBoxSelectProject")
        self.gridLayout_2.addWidget(self.comboBoxSelectProject, 1, 0, 1, 3)
        self.comboBoxSelectBackup = QtGui.QComboBox(MenuProjectBackup)
        self.comboBoxSelectBackup.setObjectName("comboBoxSelectBackup")
        self.gridLayout_2.addWidget(self.comboBoxSelectBackup, 3, 0, 1, 3)

        self.retranslateUi(MenuProjectBackup)
        self.comboBoxSelectProject.setCurrentIndex(-1)
        QtCore.QObject.connect(self.radioButtonRestoreNew, QtCore.SIGNAL("toggled(bool)"), self.labelNeLocation.setEnabled)
        QtCore.QObject.connect(self.radioButtonRestoreNew, QtCore.SIGNAL("toggled(bool)"), self.lineEditProjectLocation.setEnabled)
        QtCore.QObject.connect(self.radioButtonRestoreNew, QtCore.SIGNAL("toggled(bool)"), self.pushButtonBrowseProjectLocation.setEnabled)
        QtCore.QObject.connect(self.radioButtonRestoreNew, QtCore.SIGNAL("toggled(bool)"), self.checkBoxCustomBackupLocation.setEnabled)
        QtCore.QObject.connect(self.checkBoxCustomBackupLocation, QtCore.SIGNAL("toggled(bool)"), self.lineEditBackupFile.setEnabled)
        QtCore.QObject.connect(self.checkBoxCustomBackupLocation, QtCore.SIGNAL("toggled(bool)"), self.pushButtonBrowseBackupFile.setEnabled)
        QtCore.QObject.connect(self.pushButtonCancel, QtCore.SIGNAL("clicked()"), MenuProjectBackup.close)
        QtCore.QObject.connect(self.pushButtonBrowseProjectLocation, QtCore.SIGNAL("clicked()"), MenuProjectBackup.update)
        QtCore.QObject.connect(self.pushButtonBrowseBackupFile, QtCore.SIGNAL("clicked()"), MenuProjectBackup.update)
        QtCore.QObject.connect(self.comboBoxSelectProject, QtCore.SIGNAL("currentIndexChanged(QString)"), MenuProjectBackup.update)
        QtCore.QObject.connect(self.checkBoxCustomBackupLocation, QtCore.SIGNAL("toggled(bool)"), self.labelBackupFile.setEnabled)
        QtCore.QObject.connect(self.pushButtonOk, QtCore.SIGNAL("clicked()"), MenuProjectBackup.update)
        QtCore.QMetaObject.connectSlotsByName(MenuProjectBackup)
        MenuProjectBackup.setTabOrder(self.pushButtonOk, self.pushButtonCancel)
        MenuProjectBackup.setTabOrder(self.pushButtonCancel, self.comboBoxSelectProject)
        MenuProjectBackup.setTabOrder(self.comboBoxSelectProject, self.comboBoxSelectBackup)
        MenuProjectBackup.setTabOrder(self.comboBoxSelectBackup, self.radioButtonRestore)
        MenuProjectBackup.setTabOrder(self.radioButtonRestore, self.radioButtonRemove)
        MenuProjectBackup.setTabOrder(self.radioButtonRemove, self.radioButtonRestoreNew)
        MenuProjectBackup.setTabOrder(self.radioButtonRestoreNew, self.checkBoxCustomBackupLocation)
        MenuProjectBackup.setTabOrder(self.checkBoxCustomBackupLocation, self.lineEditProjectLocation)
        MenuProjectBackup.setTabOrder(self.lineEditProjectLocation, self.pushButtonBrowseProjectLocation)
        MenuProjectBackup.setTabOrder(self.pushButtonBrowseProjectLocation, self.lineEditBackupFile)
        MenuProjectBackup.setTabOrder(self.lineEditBackupFile, self.pushButtonBrowseBackupFile)

    def retranslateUi(self, MenuProjectBackup):
        MenuProjectBackup.setWindowTitle(QtGui.QApplication.translate("MenuProjectBackup", "Rapuma - Manage Backups", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectProject.setText(QtGui.QApplication.translate("MenuProjectBackup", "Select Project", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectBackup.setText(QtGui.QApplication.translate("MenuProjectBackup", "Select Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxBackupAction.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Define the action to be taken", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxBackupAction.setTitle(QtGui.QApplication.translate("MenuProjectBackup", "Select Action", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonBackup.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Backup the currently selected local project", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonBackup.setText(QtGui.QApplication.translate("MenuProjectBackup", "Backup Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRestore.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Restore a backup to the local project area (Note this replaces all current data, be careful)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRestore.setText(QtGui.QApplication.translate("MenuProjectBackup", "Restore Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRemove.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Remove a backup from this project backup storage area", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRemove.setText(QtGui.QApplication.translate("MenuProjectBackup", "Remove Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRestoreNew.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Restore a backup as a new project. Note, there cannot be any other projects with the same ID on your system", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRestoreNew.setText(QtGui.QApplication.translate("MenuProjectBackup", "Restore As New", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxCustomBackupLocation.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Restore a backup from outside the system", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxCustomBackupLocation.setText(QtGui.QApplication.translate("MenuProjectBackup", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNeLocation.setText(QtGui.QApplication.translate("MenuProjectBackup", "New Location (Folder)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseProjectLocation.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Browse to a location to restore a backup", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseProjectLocation.setText(QtGui.QApplication.translate("MenuProjectBackup", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBackupFile.setText(QtGui.QApplication.translate("MenuProjectBackup", "Backup File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseBackupFile.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Browse to backup file you wish to restore", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseBackupFile.setText(QtGui.QApplication.translate("MenuProjectBackup", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditProjectLocation.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Path to a location to restore a backup to", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditBackupFile.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Path to a backup file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOk.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Manage a backup operation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOk.setText(QtGui.QApplication.translate("MenuProjectBackup", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Cancel this operation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("MenuProjectBackup", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectProject.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Select project to restore a backup to", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectBackup.setToolTip(QtGui.QApplication.translate("MenuProjectBackup", "Select a backup to restore", None, QtGui.QApplication.UnicodeUTF8))

