#!/usr/bin/python
# -*- coding: utf-8 -*-

# By Dennis Drescher (sparkycbr at gmail dot com)

# Import standard modules
import os, sys, time, datetime
from configobj import ConfigObj
# Temporay mod the Python path to import auxillary modules
sys.path.insert(0, os.path.join(os.path.dirname(sys.argv[0]), 'lib'))
import sh
del sys.path[0]

# Get time/date stamp
dts             = datetime.datetime.fromtimestamp(time.time()).strftime('%Y%m%d%H%M%S')

# Get the repo version by using sh to call the git describe command
gv              = str(sh.git.describe('master')).strip().split('-')

# Make the new version number
systemVersion   = gv[0] + '.' + gv[1].zfill(3) + ' testing(' + dts + ')'

# Set the new version number
sysConfig = ConfigObj(os.path.join(os.getcwd(), 'config', 'system.ini'), encoding='utf-8')
sysConfig['Rapuma']['systemVersion'] = systemVersion
sysConfig.write()

# Report the version
print 'Version set to: ' + sysConfig['Rapuma']['systemVersion']

