#!/usr/bin/python
# -*- coding: utf-8 -*-

#    Copyright 2014, SIL International
#    All rights reserved.
#
#    This library is free software; you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published
#    by the Free Software Foundation; either version 2.1 of License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should also have received a copy of the GNU Lesser General Public
#    License along with this library in the file named "LICENSE".
#    If not, write to the Free Software Foundation, 51 Franklin Street,
#    suite 500, Boston, MA 02110-1335, USA or visit their web page on the 
#    internet at http://www.fsf.org/licenses/lgpl.html.

# Import standard modules
import os, sys
from configobj import ConfigObj
# Temporay mod the Python path to import auxillary modules
sys.path.insert(0, os.path.join(os.path.dirname(sys.argv[0]), 'lib'))
import sh
del sys.path[0]

# Update version number
gv              = str(sh.git.describe('master')).strip().split('-')
systemVersion   = gv[0] + '.' + gv[1].zfill(3) + ' build(' + gv[2] + ')'

sysConfig = ConfigObj(os.path.join(os.getcwd(), 'config', 'system.ini'), encoding='utf-8')
sysConfig['Rapuma']['systemVersion'] = systemVersion
sysConfig.write()

# Report the version
print 'Version set to: ' + sysConfig['Rapuma']['systemVersion']

