#!/usr/bin/python
# -*- coding: utf_8 -*-
# version: 20111207
# By Dennis Drescher (dennis_drescher at sil.org)

###############################################################################
######################### Description/Documentation ###########################
###############################################################################

# Simple USFM data for general operations that need it.


###############################################################################
################################# Project Class ###############################
###############################################################################
# Firstly, import all the standard Python modules we need for
# this process

import os


###############################################################################
################################## Begin Class ################################
###############################################################################

# As we load the module we will bring in all the common information about all the
# components this type will handle.

class UsfmData (object) :
    '''This class contains information about USFM components and functions
    to create various dictionaries to facilitate data varification, etc.'''


    def otCidList (self) :
        '''Return a list of OT CIDs in proper canonical order.'''

        result = []
        for name, booknum in self.bookAbbrevs.iteritems() :
            # Filter out everything but NT books
            if (booknum > 39):
                continue  # Skip this one
            # Append the CID to the list
            if name in self.usfmCidInfo :
                result.append(name)
        # Sort and return the list
        return sorted(result, key=self.canonical_order)


    def ntCidList (self) :
        '''Return a list of NT CIDs in proper canonical order.'''

        result = []
        for name, booknum in self.bookAbbrevs.iteritems() :
            # Filter out everything but NT books
            if (booknum < 61):
                continue  # Skip this one
            # Append the CID to the list
            if name in self.usfmCidInfo :
                result.append(name)
        # Sort and return the list
        return sorted(result, key=self.canonical_order)


    def bibleCidList (self) :
        '''Return a list of common Bible CIDs in proper canonical order.'''

        return self.otCidList() + self.ntCidList()


    def wholeCanonList (self) :
        '''Return a list of CIDs for the entire canon of Scripture in
        proper order. This can be used for varification of common
        components of the canon but has not been comprehensively tested.'''

        result = []
        for name, booknum in self.bookAbbrevs.iteritems() :
            # Append the CID to the list
            if name in self.usfmCidInfo :
                result.append(name)
        # Sort and return the list
        return sorted(result, key=self.canonical_order)


    def cidNameDict (self) :
        '''Return a dictionary of proper names for CIDs based on
        names found in usfmCidInfo.'''

        result = {}
        for key in self.usfmCidInfo :
            result[key] = self.usfmCidInfo[key][0]
            
        return result


    def cidChapNumDict (self) :
        '''Return a dictionary of total chapters for CIDs based on
        names found in usfmCidInfo.'''

        result = {}
        for key in self.usfmCidInfo :
            result[key] = self.usfmCidInfo[key][3]
            
        return result


    def cidPtIdDict (self) :
        '''Return a dictionary of Paratext ID numbers for CIDs based on
        names found in usfmCidInfo.'''

        result = {}
        for key in self.usfmCidInfo :
            result[key] = self.usfmCidInfo[key][2]
            
        return result


    def canonListSort (self, cidList) :
        '''Return a list of unique CIDs sorted to canon order from a 
        list of random ordered CIDs.'''

        # Sort and return the list without duplicates
        return sorted(list(set(cidList)), key=self.canonical_order)


    # Return a dictionary of all valid information about USFMs used in PT. Note
    # that a couple special non-standard IDs have been added at the top of the list.
    usfmCidInfo = {
    #        ID     Comp Name                           Comp ID                   PT ID  Chps
        
            'gen' : ['Genesis',                         'genesis',                '01',  50], 
            'exo' : ['Exodus',                          'exodus',                 '02',  40], 
            'lev' : ['Leviticus',                       'leviticus',              '03',  27], 
            'num' : ['Numbers',                         'numbers',                '04',  36], 
            'deu' : ['Deuteronomy',                     'deuteronomy',            '05',  34], 
            'jos' : ['Joshua',                          'joshua',                 '06',  24], 
            'jdg' : ['Judges',                          'judges',                 '07',  21], 
            'rut' : ['Ruth',                            'ruth',                   '08',   4], 
            '1sa' : ['1 Samuel',                        '1_samuel',               '09',  31], 
            '2sa' : ['2 Samuel',                        '2_samuel',               '10',  24], 
            '1ki' : ['1 Kings',                         '1_kings',                '11',  22], 
            '2ki' : ['2 Kings',                         '2_kings',                '12',  25], 
            '1ch' : ['1 Chronicles',                    '1_chronicles',           '13',  29], 
            '2ch' : ['2 Chronicles',                    '2_chronicles',           '14',  36], 
            'ezr' : ['Ezra',                            'ezra',                   '15',  10], 
            'neh' : ['Nehemiah',                        'nehemiah',               '16',  13], 
            'est' : ['Esther',                          'esther',                 '17',  10], 
            'job' : ['Job',                             'job',                    '18',  42], 
            'psa' : ['Psalms',                          'psalms',                 '19', 150], 
            'pro' : ['Proverbs',                        'proverbs',               '20',  31], 
            'ecc' : ['Ecclesiastes',                    'ecclesiastes',           '21',  12], 
            'sng' : ['Song of Songs',                   'song_of_songs',          '22',   8], 
            'isa' : ['Isaiah',                          'isaiah',                 '23',  66], 
            'jer' : ['Jeremiah',                        'jeremiah',               '24',  52], 
            'lam' : ['Lamentations',                    'lamentations',           '25',   5], 
            'ezk' : ['Ezekiel',                         'ezekiel',                '26',  48], 
            'dan' : ['Daniel',                          'daniel',                 '27',  12], 
            'hos' : ['Hosea',                           'hosea',                  '28',  14], 
            'jol' : ['Joel',                            'joel',                   '29',   3], 
            'amo' : ['Amos',                            'amos',                   '30',   9], 
            'oba' : ['Obadiah',                         'obadiah',                '31',   1], 
            'jon' : ['Jonah',                           'jonah',                  '32',   4], 
            'mic' : ['Micah',                           'micah',                  '33',   7], 
            'nam' : ['Nahum',                           'nahum',                  '34',   3], 
            'hab' : ['Habakkuk',                        'habakkuk',               '35',   3], 
            'zep' : ['Zephaniah',                       'zephaniah',              '36',   3], 
            'hag' : ['Haggai',                          'haggai',                 '37',   2], 
            'zec' : ['Zechariah',                       'zechariah',              '38',  14], 
            'mal' : ['Malachi',                         'malachi',                '39',   4],
            'mat' : ['Matthew',                         'matthew',                '41',  28], 
            'mrk' : ['Mark',                            'mark',                   '42',  16], 
            'luk' : ['Luke',                            'luke',                   '43',  24], 
            'jhn' : ['John',                            'john',                   '44',  21], 
            'act' : ['Acts',                            'acts',                   '45',  28], 
            'rom' : ['Romans',                          'romans',                 '46',  16], 
            '1co' : ['1 Corinthians',                   '1_corinthians',          '47',  16], 
            '2co' : ['2 Corinthians',                   '2_corinthians',          '48',  13], 
            'gal' : ['Galatians',                       'galatians',              '49',   6], 
            'eph' : ['Ephesians',                       'ephesians',              '50',   6], 
            'php' : ['Philippians',                     'philippians',            '51',   4], 
            'col' : ['Colossians',                      'colossians',             '52',   4], 
            '1th' : ['1 Thessalonians',                 '1_thessalonians',        '53',   5], 
            '2th' : ['2 Thessalonians',                 '2_thessalonians',        '54',   3], 
            '1ti' : ['1 Timothy',                       '1_timothy',              '55',   6], 
            '2ti' : ['2 Timothy',                       '2_timothy',              '56',   4], 
            'tit' : ['Titus',                           'titus',                  '57',   3], 
            'phm' : ['Philemon',                        'philemon',               '58',   1], 
            'heb' : ['Hebrews',                         'hebrews',                '59',  13], 
            'jas' : ['James',                           'james',                  '60',   5], 
            '1pe' : ['1 Peter',                         '1_peter',                '61',   5], 
            '2pe' : ['2 Peter',                         '2_peter',                '62',   3], 
            '1jn' : ['1 John',                          '1_john',                 '63',   5], 
            '2jn' : ['2 John',                          '2_john',                 '64',   1], 
            '3jn' : ['3 John',                          '3_john',                 '65',   1], 
            'jud' : ['Jude',                            'jude',                   '66',   1], 
            'rev' : ['Revelation',                      'revelation',             '67',  22], 
            'tob' : ['Tobit',                           'tobit',                  '68', '?'], 
            'jdt' : ['Judith',                          'judith',                 '69', '?'], 
            'esg' : ['Esther',                          'esther',                 '70', '?'], 
            'wis' : ['Wisdom of Solomon',               'wisdom_of_solomon',      '71', '?'], 
            'sir' : ['Sirach',                          'sirach',                 '72', '?'], 
            'bar' : ['Baruch',                          'baruch',                 '73', '?'], 
            'lje' : ['Letter of Jeremiah',              'letter_of_jeremiah',     '74', '?'], 
            's3y' : ['Song of the Three Children',      'song_3_children',        '75', '?'], 
            'sus' : ['Susanna',                         'susanna',                '76', '?'], 
            'bel' : ['Bel and the Dragon',              'bel_dragon',             '77', '?'], 
            '1ma' : ['1 Maccabees',                     '1_maccabees',            '78', '?'], 
            '2ma' : ['2 Maccabees',                     '2_maccabees',            '79', '?'], 
            '3ma' : ['3 Maccabees',                     '3_maccabees',            '80', '?'], 
            '4ma' : ['4 Maccabees',                     '4_maccabees',            '81', '?'], 
            '1es' : ['1 Esdras',                        '1_esdras',               '82', '?'], 
            '2es' : ['2 Esdras',                        '2_esdras',               '83', '?'], 
            'man' : ['Prayer of Manasses',              'prayer_of_manasses',     '84', '?'], 
            'ps2' : ['Psalms 151',                      'psalms_151',             '85', '?'], 
            'oda' : ['Odae',                            'odae',                   '86', '?'], 
            'pss' : ['Psalms of Solomon',               'psalms_of_solomon',      '87', '?'], 
            'jsa' : ['Joshua A',                        'joshua_a',               '88', '?'], 
            'jdb' : ['Joshua B',                        'joshua_b',               '89', '?'], 
            'tbs' : ['Tobit S',                         'tobit_s',                '90', '?'], 
            'sst' : ['Susannah (Theodotion)',           'susannah_t',             '91', '?'], 
            'dnt' : ['Daniel (Theodotion)',             'daniel_t',               '92', '?'], 
            'blt' : ['Bel and the Dragon (Theodotion)', 'bel_dragon_t',           '93', '?'], 
            'frt' : ['Front Matter',                    'front_matter',           'A0',   0], 
            'int' : ['Introductions',                   'introductions',          'A7',   0], 
            'bak' : ['Back Matter',                     'back_matter',            'A1',   0], 
            'cnc' : ['Concordance',                     'concordance',            'A8',   0], 
            'glo' : ['Glossary',                        'glossary',               'A9',   0], 
            'tdx' : ['Topical Index',                   'topical_index',          'B0',   0], 
            'ndx' : ['Names Index',                     'names_index',            'B1',   0], 
            'xxa' : ['Extra A',                         'extra_a',                '94',   0], 
            'xxb' : ['Extra B',                         'extra_b',                '95',   0], 
            'xxc' : ['Extra C',                         'extra_c',                '96',   0], 
            'xxd' : ['Extra D',                         'extra_d',                '97',   0],
            'xxe' : ['Extra E',                         'extra_e',                '98',   0], 
            'xxf' : ['Extra F',                         'extra_f',                '99',   0], 
            'xxg' : ['Extra G',                         'extra_g',                '100',  0], 
            'oth' : ['Other',                           'other',                  'A2',   0], 
            'eza' : ['Apocalypse of Ezra',              'apocalypse_of_ezra',     'A4', '?'], 
            '5ez' : ['5 Ezra',                          '5_ezra_lp',              'A5', '?'], 
            '6ez' : ['6 Ezra (Latin Epilogue)',         '6_ezra_lp',              'A6', '?'], 
            'dag' : ['Daniel Greek',                    'daniel_greek',           'B2', '?'], 
            'ps3' : ['Psalms 152-155',                  'psalms_152-155',         'B3', '?'], 
            '2ba' : ['2 Baruch (Apocalypse)',           '2_baruch_apocalypse',    'B4', '?'], 
            'lba' : ['Letter of Baruch',                'letter_of_baruch',       'B5', '?'], 
            'jub' : ['Jubilees',                        'jubilees',               'B6', '?'], 
            'eno' : ['Enoch',                           'enoch',                  'B7', '?'], 
            '1mq' : ['1 Meqabyan',                      '1_meqabyan',             'B8', '?'], 
            '2mq' : ['2 Meqabyan',                      '2_meqabyan',             'B9', '?'], 
            '3mq' : ['3 Meqabyan',                      '3_meqabyan',             'C0', '?'], 
            'rep' : ['Reproof (Proverbs 25-31)',        'reproof_proverbs_25-31', 'C1', '?'], 
            '4ba' : ['4 Baruch (Rest of Baruch)',       '4_baruch',               'C2', '?'], 
            'lao' : ['Laodiceans',                      'laodiceans',             'C3', '?'] 
            }


    def canonical_order(self, book) :
        '''Drawing on the data in the book abbreviations dictionary, 
        simply return the canonical order of a specific (book) cid.'''

        return self.bookAbbrevs[book]


    # Return a dictionary with all Bible names and abbreviations
    # with their proper canonical order. This data comes from the
    # Libronix project (http://www.libronix.com/) and has been adapted
    # to harmonize with the PT data set (usfmCidInfo)
    canonBookAbbrevs = {

            "ge" : 1,
            "gn" : 1,
            "gen" : 1,
            "genesis" : 1,
            "1mo" : 1,
            "1 mo" : 1,
            "1mos" : 1,
            "1 mos" : 1,
            "1moses" : 1,
            "1 moses" : 1,
            "i mo" : 1,
            "i mos" : 1,
            "i moses" : 1,
            "ex" : 2,
            "exo" : 2,
            "exod" : 2,
            "exodus" : 2,
            "2mo" : 2,
            "2 mo" : 2,
            "2mos" : 2,
            "2 mos" : 2,
            "2moses" : 2,
            "2 moses" : 2,
            "ii mo" : 2,
            "ii mos" : 2,
            "ii moses" : 2,
            "le" : 3,
            "lv" : 3,
            "lev" : 3,
            "leviticus" : 3,
            "3mo" : 3,
            "3 mo" : 3,
            "3mos" : 3,
            "3 mos" : 3,
            "3moses" : 3,
            "3 moses" : 3,
            "iii mo" : 3,
            "iii mos" : 3,
            "iii moses" : 3,
            "nm" : 4,
            "nu" : 4,
            "num" : 4,
            "number" : 4,
            "numbers" : 4,
            "4mo" : 4,
            "4 mo" : 4,
            "4mos" : 4,
            "4 mos" : 4,
            "4moses" : 4,
            "4 moses" : 4,
            "iv mo" : 4,
            "iv mos" : 4,
            "iv moses" : 4,
            "de" : 5,
            "dt" : 5,
            "deu" : 5,
            "dtn" : 5,
            "deut" : 5,
            "deuteronomy" : 5,
            "5mo" : 5,
            "5 mo" : 5,
            "5mos" : 5,
            "5 mos" : 5,
            "5moses" : 5,
            "5 moses" : 5,
            "v mo" : 5,
            "v mos" : 5,
            "v moses" : 5,
            "jos" : 6,
            "josh" : 6,
            "joshua" : 6,
            "jdg" : 7,
            "jgs" : 7,
            "judg" : 7,
            "judge" : 7,
            "judges" : 7,
            "ru" : 8,
            "rut" : 8,
            "ruth" : 8,
            "1s" : 9,
            "1 s" : 9,
            "1sa" : 9,
            "1 sa" : 9,
            "1sm" : 9,
            "1 sm" : 9,
            "1sam" : 9,
            "1 sam" : 9,
            "1samuel" : 9,
            "1 samuel" : 9,
            "1kgdms" : 9,
            "1 kgdms" : 9,
            "1kingdoms" : 9,
            "1 kingdoms" : 9,
            "i s" : 9,
            "i sa" : 9,
            "i sm" : 9,
            "i sam" : 9,
            "i samuel" : 9,
            "i kgdms" : 9,
            "i kingdoms" : 9,
            "2s" : 10,
            "2 s" : 10,
            "2sa" : 10,
            "2 sa" : 10,
            "2sm" : 10,
            "2 sm" : 10,
            "2sam" : 10,
            "2 sam" : 10,
            "2samuel" : 10,
            "2 samuel" : 10,
            "2kgdms" : 10,
            "2 kgdms" : 10,
            "2kingdoms" : 10,
            "2 kingdoms" : 10,
            "ii s" : 10,
            "ii sa" : 10,
            "ii sm" : 10,
            "ii sam" : 10,
            "ii samuel" : 10,
            "ii kgdms" : 10,
            "ii kingdoms" : 10,
            "1k" : 11,
            "1 k" : 11,
            "1kg" : 11,
            "1 kg" : 11,
            "1ki" : 11,
            "1 ki" : 11,
            "1kgs" : 11,
            "1 kgs" : 11,
            "1king" : 11,
            "1 king" : 11,
            "1kings" : 11,
            "1 kings" : 11,
            "i k" : 11,
            "i kg" : 11,
            "i ki" : 11,
            "i kgs" : 11,
            "i king" : 11,
            "i kings" : 11,
            # In some Bibles, 1 Samuel, 2 Samuel, 1 Kings, 2 Kings, is called
            #  1 Kings, 2 Kings, 3 Kings, 4 Kings.
            # Although we can't support the equivalence 1 Samuel = 1 Kings and
            #  2 Samuel = 2 Kings because it would mean a multivalued dictionary entry,
            #  we do support 1 Kings = 3 Kings and 2 Kings = 4 Kings.
            "3k" : 11,
            "3 k" : 11,
            "3kg" : 11,
            "3 kg" : 11,
            "3ki" : 11,
            "3 ki" : 11,
            "3kgs" : 11,
            "3 kgs" : 11,
            "3king" : 11,
            "3 king" : 11,
            "3kings" : 11,
            "3 kings" : 11,
            "3kgdms" : 11,
            "3 kgdms" : 11,
            "3kingdoms" : 11,
            "3 kingdoms" : 11,
            "iii k" : 11,
            "iii kg" : 11,
            "iii ki" : 11,
            "iii kgs" : 11,
            "iii king" : 11,
            "iii kings" : 11,
            "iii kgdms" : 11,
            "iii kingdoms" : 11,
            "2k" : 12,
            "2 k" : 12,
            "2kg" : 12,
            "2 kg" : 12,
            "2ki" : 12,
            "2 ki" : 12,
            "2kgs" : 12,
            "2 kgs" : 12,
            "2king" : 12,
            "2 king" : 12,
            "2kings" : 12,
            "2 kings" : 12,
            "ii k" : 12,
            "ii kg" : 12,
            "ii ki" : 12,
            "ii kgs" : 12,
            "ii king" : 12,
            "ii kings" : 12,
            "4k" : 12,
            "4 k" : 12,
            "4kg" : 12,
            "4 kg" : 12,
            "4ki" : 12,
            "4 ki" : 12,
            "4kgs" : 12,
            "4 kgs" : 12,
            "4king" : 12,
            "4 king" : 12,
            "4kings" : 12,
            "4 kings" : 12,
            "4kgdms" : 12,
            "4 kgdms" : 12,
            "4kingdoms" : 12,
            "4 kingdoms" : 12,
            "iv k" : 12,
            "iv kg" : 12,
            "iv ki" : 12,
            "iv kgs" : 12,
            "iv king" : 12,
            "iv kings" : 12,
            "iv kgdms" : 12,
            "iv kingdoms" : 12,
            "1ch" : 13,
            "1 ch" : 13,
            "1chr" : 13,
            "1 chr" : 13,
            "1chron" : 13,
            "1 chron" : 13,
            "1chronicle" : 13,
            "1 chronicle" : 13,
            "1chronicles" : 13,
            "1 chronicles" : 13,
            "i ch" : 13,
            "i chr" : 13,
            "i chron" : 13,
            "i chronicle" : 13,
            "i chronicles" : 13,
            "2ch" : 14,
            "2 ch" : 14,
            "2chr" : 14,
            "2 chr" : 14,
            "2chron" : 14,
            "2 chron" : 14,
            "2chronicle" : 14,
            "2 chronicle" : 14,
            "2chronicles" : 14,
            "2 chronicles" : 14,
            "ii ch" : 14,
            "ii chr" : 14,
            "ii chron" : 14,
            "ii chronicle" : 14,
            "ii chronicles" : 14,
            "ezr" : 15,
            "ezra" : 15,
            "ne" : 16,
            "neh" : 16,
            "nehemiah" : 16,
            "es" : 17,
            "est" : 17,
            "esth" : 17,
            "esther" : 17,
            "jb" : 18,
            "job" : 18,
            "ps" : 19,
            "psa" : 19,
            # In PT the "pss" label is for "Psalms of Solomon". To
            # harmonize with the PT data set, this will be commented
            # out here and moved to the entry for Psalms of Solomon #59.
            # (djd - 23 May 2014) 
            #"pss" : 19,
            "psalm" : 19,
            "psalms" : 19,
            "pr" : 20,
            "pro" : 20,
            "prv" : 20,
            "prov" : 20,
            "proverb" : 20,
            "proverbs" : 20,
            "ec" : 21,
            "ecc" : 21,
            "eccl" : 21,
            "eccles" : 21,
            "ecclesiastes" : 21,
            "sg" : 22,
            "so" : 22,
            "ss" : 22,
            "sng" : 22,
            "song" : 22,
            "song of sol" : 22,
            "song of song" : 22,
            "song of songs" : 22,
            "song of solomon" : 22,
            "cant" : 22,
            "cant of cant" : 22,
            "canticles" : 22,
            "canticle of canticles" : 22,
            "is" : 23,
            "isa" : 23,
            "isaiah" : 23,
            "je" : 24,
            "jr" : 24,
            "jer" : 24,
            "jeremiah" : 24,
            "la" : 25,
            "lam" : 25,
            "lamentation" : 25,
            "lamentations" : 25,
            "ez" : 26,
            "eze" : 26,
            "ezk" : 26,
            "ezek" : 26,
            "ezekiel" : 26,
            "da" : 27,
            "dn" : 27,
            "dan" : 27,
            "dnl" : 27,
            "daniel" : 27,
            "ho" : 28,
            "hos" : 28,
            "hosea" : 28,
            "jl" : 29,
            "joe" : 29,
            # The "jol" ID is found in the PT data set but was missing
            # from this data set so it has been added. (djd - 23 May 2014)
            "jol" : 29,
            "joel" : 29,
            "am" : 30,
            "amo" : 30,
            "amos" : 30,
            "ob" : 31,
            "oba" : 31,
            "obad" : 31,
            "obadiah" : 31,
            "jon" : 32,
            "jonah" : 32,
            "mi" : 33,
            "mic" : 33,
            "micah" : 33,
            "na" : 34,
            "nah" : 34,
            # The "nam" ID is found in the PT data set but was missing
            # from this data set so it has been added. (djd - 23 May 2014)
            "nam" : 34,
            "nahum" : 34,
            "hb" : 35,
            "hab" : 35,
            "habakkuk" : 35,
            "zp" : 36,
            "zep" : 36,
            "zeph" : 36,
            "zephaniah" : 36,
            "hg" : 37,
            "hag" : 37,
            "haggai" : 37,
            "zc" : 38,
            "zec" : 38,
            "zech" : 38,
            "zechariah" : 38,
            "mal" : 39,
            "malachi" : 39,
            
            # The numbers for the Apocrypha were given to Bruce from 
            # Libronix via Larry Waswick 2006 April 19:
            #  40 Tob     Tobit
            #  41 Jdt     Judith
            #  42 Add Es  Additions to Esther
            #  43 Wis     Wisdom of Solomon
            #  44 Sir     Sirach (Ecclesiasticus, Wisdom of Ben Sira)
            #  45 Bar     Baruch
            #  46 LJe     Letter of Jeremiah
            #  47 Pr Az   Prayer of Azariah (Song of Three Youths, etc.)
            #  48 Sus     Susanna
            #  49 Bel     Bel and the Dragon
            #  50 1Ma     1 Maccabees
            #  51 2Ma     2 Maccabees
            #  52 1Es     1 Esdras
            #  53 Pr Man  Prayer of Manasseh
            #  54 Add Ps  Additional Psalm (Psalm 151)
            #  55 3Ma     3 Maccabees
            #  56 2Es     2 Esdras
            #  57 4Ma     4 Maccabees
            #  58 Ode     Ode
            #  59 Ps Sol  Psalm of Solomon
            #  60 Laod    Laodiceans
            
            "tb" : 40,
            "to" : 40,
            "tob" : 40,
            "tobias" : 40,
            "tobit" : 40,
            "jdt" : 41,
            "judith" : 41,
            "ad es" : 42,
            "ad. es" : 42,
            "addes" : 42,
            "add es" : 42,
            "add. es" : 42,
            "add est" : 42,
            "add. est" : 42,
            "add esth" : 42,
            "add. esth" : 42,
            "rest of esther" : 42,
            "additions to esther" : 42,
            "ws" : 43,
            "wis" : 43,
            "wisd" : 43,
            "wisdom" : 43,
            "wisd sol" : 43,
            "wisdom of solomon" : 43,
            "si" : 44,
            "sir" : 44,
            "sirach" : 44,
            "wisdom of sirach" : 44,
            "wisdom of ben sira" : 44,
            "wisdom of yeshua ben sira" : 44,
            "ecclus" : 44,
            "ecclesiasticus" : 44,
            "ba" : 45,
            "bar" : 45,
            "baruch" : 45,
            "lje" : 46,
            "epistle of jeremy" : 46,
            "epistle of jeremiah" : 46,
            "letter of jeremiah" : 46,
            "az" : 47,
            "aza" : 47,
            "pr az" : 47,
            "pr aza" : 47,
            "azariah" : 47,
            "pr of az" : 47,
            "pr of aza" : 47,
            "prayer of azariah" : 47,
            "the prayer of azariah" : 47,
            "song of three youths" : 47,
            "song of three children" : 47,
            "song of the three youths" : 47,
            "song of the three children" : 47,
            "song of three holy children" : 47,
            "song of the three holy children" : 47,
            "the prayer of azariah and song of the three holy children" : 47,
            "su" : 48,
            "sus" : 48,
            "susanna" : 48,
            "book of susanna" : 48,
            "the book of susanna" : 48,
            "bel" : 49,
            "bel and dragon" : 49,
            "bel and the dragon" : 49,
            "book of bel and dragon" : 49,
            "book of bel and the dragon" : 49,
            "the book of bel and the dragon" : 49,
            "1m" : 50,
            "1 m" : 50,
            "1ma" : 50,
            "1 ma" : 50,
            "1mc" : 50,
            "1 mc" : 50,
            "1mac" : 50,
            "1 mac" : 50,
            "1macc" : 50,
            "1 macc" : 50,
            "1maccabee" : 50,
            "1 maccabee" : 50,
            "1maccabees" : 50,
            "1 maccabees" : 50,
            "first maccabee" : 50,
            "first maccabees" : 50,
            "first book of maccabee" : 50,
            "first book of maccabees" : 50,
            "the first book of maccabee" : 50,
            "the first book of maccabees" : 50,
            "i m" : 50,
            "i ma" : 50,
            "i mc" : 50,
            "i mac" : 50,
            "i macc" : 50,
            "i maccabee" : 50,
            "i maccabees" : 50,
            "2m" : 51,
            "2 m" : 51,
            "2ma" : 51,
            "2 ma" : 51,
            "2mc" : 51,
            "2 mc" : 51,
            "2mac" : 51,
            "2 mac" : 51,
            "2macc" : 51,
            "2 macc" : 51,
            "2maccabee" : 51,
            "2 maccabee" : 51,
            "2maccabees" : 51,
            "2 maccabees" : 51,
            "second maccabee" : 51,
            "second maccabees" : 51,
            "second book of maccabee" : 51,
            "second book of maccabees" : 51,
            "the second book of maccabee" : 51,
            "the second book of maccabees" : 51,
            "ii m" : 51,
            "ii ma" : 51,
            "ii mc" : 51,
            "ii mac" : 51,
            "ii macc" : 51,
            "ii maccabee" : 51,
            "ii maccabees" : 51,
            # The modern books of Ezra, Nehemiah, 1 Esdras, and 2 
            # Esdras were called 1 Esdras, 2 Esdras, 3 Esdras, and 
            # 4 Esdras by Jerome. To complicate matters even 
            # further, the Eastern Orthodox Churches has a book with 
            # material largely taken from Ezra and Nehemiah, called 
            # 1 Esdras, then 1 Esdras and 2 Esdras are called 2 
            # Esdras and 3 Esdras. Although we can't support the 
            # equivalence Ezra = 1 Esdras and Nehemiah = 2 Esdras 
            # because it would mean a multivalued dictionary entry, 
            # we do support 1 Esdras = 3 Esdras and 2 Esdras = 4 
            # Esdras. Unfortunately, we can't support the Russian 
            # Orthodox labelling scheme as well.
            "1es" : 52,
            "1 es" : 52,
            "1esd" : 52,
            "1 esd" : 52,
            "1esdras" : 52,
            "1 esdras" : 52,
            "i es" : 52,
            "i esd" : 52,
            "i esdras" : 52,
            "3es" : 52,
            "3 es" : 52,
            "3esd" : 52,
            "3 esd" : 52,
            "3esdras" : 52,
            "3 esdras" : 52,
            "iii es" : 52,
            "iii esd" : 52,
            "iii esdras" : 52,
            "man" : 53,
            "pr man" : 53,
            "pr of man" : 53,
            "manasseh" : 53,
            "manassas" : 53,
            "prayer of manassas" : 53,
            "prayer of manasseh" : 53,
            "the prayer of manasseh" : 53,
            "the prayer of manassas" : 53,
            "add ps" : 54,  # Psalm 151
            "additional psalm" : 54,
            "3m" : 55,
            "3 m" : 55,
            "3ma" : 55,
            "3 ma" : 55,
            "3mc" : 55,
            "3 mc" : 55,
            "3mac" : 55,
            "3 mac" : 55,
            "3macc" : 55,
            "3 macc" : 55,
            "3maccabee" : 55,
            "3 maccabee" : 55,
            "3maccabees" : 55,
            "3 maccabees" : 55,
            "third maccabee" : 55,
            "third maccabees" : 55,
            "third book of maccabee" : 55,
            "third book of maccabees" : 55,
            "the third book of maccabee" : 55,
            "the third book of maccabees" : 55,
            "iii m" : 55,
            "iii ma" : 55,
            "iii mc" : 55,
            "iii mac" : 55,
            "iii macc" : 55,
            "iii maccabee" : 55,
            "iii maccabees" : 55,
            # See the discussion of 1 Esdras above
            "2es" : 56,
            "2 es" : 56,
            "2esd" : 56,
            "2 esd" : 56,
            "2esdras" : 56,
            "2 esdras" : 56,
            "ii es" : 56,
            "ii esd" : 56,
            "ii esdras" : 56,
            "4es" : 56,
            "4 es" : 56,
            "4esd" : 56,
            "4 esd" : 56,
            "4esdras" : 56,
            "4 esdras" : 56,
            "iv es" : 56,
            "iv esd" : 56,
            "iv esdras" : 56,
            "4m" : 57,
            "4 m" : 57,
            "4ma" : 57,
            "4 ma" : 57,
            "4mc" : 57,
            "4 mc" : 57,
            "4mac" : 57,
            "4 mac" : 57,
            "4macc" : 57,
            "4 macc" : 57,
            "4maccabee" : 57,
            "4 maccabee" : 57,
            "4maccabees" : 57,
            "4 maccabees" : 57,
            "fourth maccabee" : 57,
            "fourth maccabees" : 57,
            "fourth book of maccabee" : 57,
            "fourth book of maccabees" : 57,
            "the fourth book of maccabee" : 57,
            "the fourth book of maccabees" : 57,
            "iv m" : 57,
            "iv ma" : 57,
            "iv mc" : 57,
            "iv mac" : 57,
            "iv macc" : 57,
            "iv maccabee" : 57,
            "iv maccabees" : 57,
            "ode" : 58,
            "ode sol" : 58,
            "ode solomon" : 58,
            "ode of solomon" : 58,
            "odes of solomon" : 58,
            # The "pss" ID in this data set was used for "Psalms" but to
            # harmonize with the PT data set it was attached to Psalms
            # of Soloman. (djd - 23 May 2014)
            "pss" : 59,
            "pssol" : 59,
            "ps sol" : 59,
            "pss sol" : 59,
            "pss. sol" : 59,
            "psalm solomon" : 59,
            "psalms solomon" : 59,
            "psalms of solomon" : 59,
            "lao" : 60,
            "laod" : 60,
            "laodicean" : 60,
            "laodiceans" : 60,
            "paul to laodicean" : 60,
            "paul to laodiceans" : 60,
            "paul to the laodicean" : 60,
            "paul to the laodiceans" : 60,
            
            # Other Apocryphal books not included in the above may be:
            #  (Book of) Jubilees
            #  (Book of) Enoch [1 Enoch]
            
            "mt" : 61,
            "mat" : 61,
            "matt" : 61,
            "matthew" : 61,
            "mk" : 62,
            "mar" : 62,
            "mrk" : 62,
            "mark" : 62,
            "lk" : 63,
            "lu" : 63,
            "luk" : 63,
            "luke" : 63,
            "jn" : 64,
            "jhn" : 64,
            "john" : 64,
            "ac" : 65,
            "act" : 65,
            "acts" : 65,
            "acts of the apostles" : 65,
            "rm" : 66,
            "ro" : 66,
            "rom" : 66,
            "roman" : 66,
            "romans" : 66,
            "1co" : 67,
            "1 co" : 67,
            "1cor" : 67,
            "1 cor" : 67,
            "1corinthian" : 67,
            "1 corinthian" : 67,
            "1corinthians" : 67,
            "1 corinthians" : 67,
            "i co" : 67,
            "i cor" : 67,
            "i corinthian" : 67,
            "i corinthians" : 67,
            "2co" : 68,
            "2cor" : 68,
            "2 co" : 68,
            "2 cor" : 68,
            "2corinthian" : 68,
            "2 corinthian" : 68,
            "2corinthians" : 68,
            "2 corinthians" : 68,
            "ii co" : 68,
            "ii cor" : 68,
            "ii corinthian" : 68,
            "ii corinthians" : 68,
            "ga" : 69,
            "gal" : 69,
            "galatian" : 69,
            "galatians" : 69,
            "ep" : 70,
            "eph" : 70,
            "ephesian" : 70,
            "ephesians" : 70,
            "php" : 71,
            "phil" : 71,
            "philippian" : 71,
            "philippians" : 71,
            "co" : 72,
            "col" : 72,
            "colossian" : 72,
            "colossians" : 72,
            "1th" : 73,
            "1 th" : 73,
            "1thes" : 73,
            "1 thes" : 73,
            "1thess" : 73,
            "1 thess" : 73,
            "1thessalonian" : 73,
            "1 thessalonian" : 73,
            "1thessalonians" : 73,
            "1 thessalonians" : 73,
            "i th" : 73,
            "i thes" : 73,
            "i thess" : 73,
            "i thessalonian" : 73,
            "i thessalonians" : 73,
            "2th" : 74,
            "2 th" : 74,
            "2thes" : 74,
            "2 thes" : 74,
            "2thess" : 74,
            "2 thess" : 74,
            "2thessalonian" : 74,
            "2 thessalonian" : 74,
            "2thessalonians" : 74,
            "2 thessalonians" : 74,
            "ii th" : 74,
            "ii thes" : 74,
            "ii thess" : 74,
            "ii thessalonian" : 74,
            "ii thessalonians" : 74,
            "1ti" : 75,
            "1 ti" : 75,
            "1tm" : 75,
            "1 tm" : 75,
            "1tim" : 75,
            "1 tim" : 75,
            "1timothy" : 75,
            "1 timothy" : 75,
            "i ti" : 75,
            "i tm" : 75,
            "i tim" : 75,
            "i timothy" : 75,
            "2ti" : 76,
            "2 ti" : 76,
            "2tm" : 76,
            "2 tm" : 76,
            "2tim" : 76,
            "2 tim" : 76,
            "2timothy" : 76,
            "2 timothy" : 76,
            "ii ti" : 76,
            "ii tm" : 76,
            "ii tim" : 76,
            "ii timothy" : 76,
            "ti" : 77,
            "tit" : 77,
            "titus" : 77,
            "phm" : 78,
            "phlm" : 78,
            "phile" : 78,
            "philem" : 78,
            "philemon" : 78,
            "he" : 79,
            "heb" : 79,
            "hebr" : 79,
            "hebrew" : 79,
            "hebrews" : 79,
            "ja" : 80,
            "jam" : 80,
            "jas" : 80,
            "jame" : 80,
            "james" : 80,
            "1p" : 81,
            "1 p" : 81,
            "1pe" : 81,
            "1 pe" : 81,
            "1pt" : 81,
            "1 pt" : 81,
            "1pet" : 81,
            "1 pet" : 81,
            "1peter" : 81,
            "1 peter" : 81,
            "i p" : 81,
            "i pe" : 81,
            "i pt" : 81,
            "i pet" : 81,
            "i peter" : 81,
            "2p" : 82,
            "2 p" : 82,
            "2pe" : 82,
            "2 pe" : 82,
            "2pt" : 82,
            "2 pt" : 82,
            "2pet" : 82,
            "2 pet" : 82,
            "2peter" : 82,
            "2 peter" : 82,
            "ii p" : 82,
            "ii pe" : 82,
            "ii pt" : 82,
            "ii pet" : 82,
            "ii peter" : 82,
            "1jn" : 83,
            "1 jn" : 83,
            "1jo" : 83,
            "1 jo" : 83,
            "1john" : 83,
            "1 john" : 83,
            "i jn" : 83,
            "i john" : 83,
            "2jn" : 84,
            "2 jn" : 84,
            "2jo" : 84,
            "2 jo" : 84,
            "2john" : 84,
            "2 john" : 84,
            "ii jn" : 84,
            "ii john" : 84,
            "3jn" : 85,
            "3 jn" : 85,
            "3jo" : 85,
            "3 jo" : 85,
            "3john" : 85,
            "3 john" : 85,
            "iii jn" : 85,
            "iii john" : 85,
            "jud" : 86,
            "jude" : 86,
            "ap" : 87,
            "apo" : 87,
            "apoc" : 87,
            "apocalypse" : 87,
            "re" : 87,
            "rv" : 87,
            "rev" : 87,
            "revelation" : 87,
            "revelations" : 87,
           
            }

    extraCompAbbrevs = {

            'frt' : 0, 
            'int' : 0, 
            'bak' : 0, 
            'cnc' : 0, 
            'glo' : 0, 
            'tdx' : 0, 
            'ndx' : 0, 
            'xxa' : 0, 
            'xxb' : 0, 
            'xxc' : 0, 
            'xxd' : 0,
            'xxe' : 0, 
            'xxf' : 0, 
            'xxg' : 0, 
            'oth' : 0 

            }

    bookAbbrevs = {}
    bookAbbrevs.update(canonBookAbbrevs)
    bookAbbrevs.update(extraCompAbbrevs)
